# Generated by Django 5.1.1 on 2024-09-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
